# Generated by Django 5.0.6 on 2024-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0005_rename_landmark_order_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ItemJson',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
