# Generated by Django 5.0.6 on 2024-06-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0008_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='product',
            name='product_desc2',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(max_length=2500),
        ),
    ]
